service: ${self:custom.name}-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: sts:AssumeRole
          Resource: ${self:custom.serviceRoleArn}
        - Effect: Allow
          Action: ssm:GetParameters*
          Resource:
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${param:ssm-stage, sls:stage}
  environment:
    SERVICE_NAME: ${self:service}
    SERVICE_ROLE_ARN: ${self:custom.serviceRoleArn}
    ROOT_DOMAIN: ${self:custom.domain}
    LOG_LEVEL: ${self:custom.logLevel.${sls:stage}, self:custom.logLevel.default}
    POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
    POWERTOOLS_LOGGER_LOG_EVENT: true
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

plugins:
  - serverless-appsync-plugin
  - serverless-esbuild
  - serverless-export-env
  - serverless-iam-roles-per-function
  - serverless-manifest-plugin

package:
  individually: true

custom:
  name: shobo-tenants
  domain: shobogonzo.dev
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  serviceRoleArn: ${ssm:/${self:service}/${self:custom.stage}/serviceRoleArn}
  esbuild:
    minify: true
    external:
      - '@aws-sdk/*'
  manifest:
    postProcess: ./utils/process-manifest.js
    disablePostDeployGeneration: true
    disableOutput: true
    silent: true
  logLevel:
    prod: ERROR
    default: INFO

appSync: ${file(serverless.appsync-api.yml)}

functions:
  createCognitoUser:
    handler: functions/create-cognito-user.handler
    environment:
      USER_POOL_ID: !Ref UserPool
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminCreateUser
          - cognito-idp:AdminAddUserToGroup
        Resource: !GetAtt UserPool.Arn

  registerUserSignup:
    handler: functions/register-user-signup.handler
    environment:
      TENANT_TABLE: !Ref TenantTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt TenantTable.Arn

  sendConfirmationEmail:
    handler: functions/send-confirmation-email.handler
    environment:
      TENANT_TABLE: !Ref TenantTable

  confirmUserSignup:
    handler: functions/confirm-user-signup.handler
    environment:
      TENANT_TABLE: !Ref TenantTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:UpdateItem
        Resource: !GetAtt TenantTable.Arn

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.name}-user-pool-${self:custom.stage}
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        AliasAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Required: true
          - Name: tenantId
            Mutable: false
            AttributeDataType: String
        LambdaConfig:
          PreSignUp: !GetAtt RegisterUserSignupLambdaFunction.Arn
          CustomMessage: !GetAtt SendConfirmationEmailLambdaFunction.Arn
          PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn

    UserPoolInvokeRegisterUserSignupLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref RegisterUserSignupLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt UserPool.Arn

    UserPoolInvokeSendConfirmationEmailLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref SendConfirmationEmailLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt UserPool.Arn

    UserPoolInvokeConfirmUserSignupLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref ConfirmUserSignupLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt UserPool.Arn

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.name}-client-${self:custom.stage}
        GenerateSecret: false
        UserPoolId: !Ref UserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_PASSWORD_AUTH
        PreventUserExistenceErrors: ENABLED

    IdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${self:custom.name}-identity-pool-${self:custom.stage}
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId: !Ref UserPoolClient
            ProviderName: !GetAtt UserPool.ProviderName

    SysAdminGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        UserPoolId: !Ref UserPool
        GroupName: SYS_ADMIN

    TenantAdminGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        UserPoolId: !Ref UserPool
        GroupName: TENANT_ADMIN

    TenantTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: expireAt
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

  Outputs:
    ServiceName:
      Value: ${self:service}
    UserPoolId:
      Value: !Ref UserPool
    UserPoolClientId:
      Value: !Ref UserPoolClient
    TenantTable:
      Value: !Ref TenantTable
    GraphQlApiUrl:
      Value: !GetAtt GraphQlApi.GraphQLUrl
